services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: notes
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_practice_go:/var/lib/postgresql/data
    ports: ["5433:5432"]

volumes:
  postgres_practice_go: