basePath: /api/v1
definitions:
  core.Note:
    properties:
      content:
        type: string
      createdAt:
        type: string
      id:
        format: int64
        type: integer
      title:
        type: string
      updatedAt:
        type: string
    type: object
  dto.CreateNoteRequest:
    properties:
      content:
        example: TestContent
        type: string
      title:
        example: TestTitle
        type: string
    type: object
  dto.NoteResponse:
    properties:
      content:
        example: TestContent
        type: string
      createdAt:
        example: "2025-12-15T12:00:00Z"
        type: string
      id:
        example: 1
        type: integer
      title:
        example: TestTitle
        type: string
      updatedAt:
        example: "2025-12-15T13:00:00Z"
        type: string
    type: object
  dto.UpdateNoteRequest:
    properties:
      content:
        example: TestContentUpdated
        type: string
      title:
        example: TestTitleUpdated
        type: string
    type: object
info:
  contact:
    email: example@university.ru
    name: Backend Course
  description: Учебный REST API для заметок (CRUD).
  title: Notes API
  version: "1.0"
paths:
  /notes:
    get:
      description: Возвращает список всех заметок
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/core.Note'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Список заметок
      tags:
      - notes
    post:
      consumes:
      - application/json
      description: Создаёт новую заметку и возвращает объект
      parameters:
      - description: Данные заметки
        in: body
        name: note
        required: true
        schema:
          $ref: '#/definitions/dto.CreateNoteRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.NoteResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Создать заметку
      tags:
      - notes
  /notes/{id}:
    delete:
      description: Удаляет заметку по ID
      parameters:
      - description: ID заметки
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: Заметка удалена
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удалить заметку
      tags:
      - notes
    get:
      description: Возвращает заметку по идентификатору
      parameters:
      - description: ID заметки
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.Note'
        "400":
          description: Некорректный ID
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Заметка не найдена
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить заметку
      tags:
      - notes
    put:
      consumes:
      - application/json
      description: Полностью обновляет заметку по ID
      parameters:
      - description: ID заметки
        format: int64
        in: path
        name: id
        required: true
        type: integer
      - description: Новые данные заметки
        in: body
        name: note
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateNoteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.NoteResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновить заметку
      tags:
      - notes
swagger: "2.0"
